[book]
title = "یادگیری ماشین قابل تفسیر"
authors = ["Christoph Molnar"]
language = "fa"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/maryam-mahmoudi/interpretable-machine-learning-persian"
edit-url-template = "https://github.com/maryam-mahmoudi/interpretable-machine-learning-persian/edit/main/chapters/{path}"

[output.html.playground]
runnable = false

[rust]
edition = "2021"
